name: Integration tests

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-18.04
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          path: swedbank-pay-woocommerce-checkout

      - name: WooCommerce Checkout
        uses: actions/checkout@v3.3.0
        with:
          repository: woocommerce/woocommerce
          ref: 5.9.0
          path: woocommerce

      - name: Install dependencies
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          extension: intl, mbstring, json, bcmath
          coverage: xdebug
          tools: composer, php-cs-fixer, phpunit:7.5.20, phpcpd, phpmd

      - name: Set up MySQL
        run: sudo systemctl start mysql.service

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: Run PHPCS inspection
        run: |
          composer global require "wp-coding-standards/wpcs"
          phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs
          cd $GITHUB_WORKSPACE/swedbank-pay-woocommerce-checkout
          phpcs --standard=WordPress-Core --report=code --ignore=woocommerce,vendors,tests,docs,build,.github,assets/js/*.min.js --runtime-set ignore_warnings_on_exit true ./

      - name: Build the plugin package
        run: |
          cd $GITHUB_WORKSPACE/swedbank-pay-woocommerce-checkout
          composer require swedbank-pay/swedbank-pay-woocommerce-core:dev-main --no-install
          composer install
          zip -q -r /tmp/swedbank-pay-woocommerce-checkout.zip ./

      - name: Build WooCommerce package
        run: |
          cd $GITHUB_WORKSPACE/woocommerce
          npm install -g grunt
          npm install
          composer install
          npm run build
          zip -q -r /tmp/woocommerce.zip ./

      - name: Build WooCommerce Test Enviroment
        run: |
          cd $GITHUB_WORKSPACE/woocommerce
          bash tests/bin/install.sh woocommerce_test root 'root' localhost latest
          cd /tmp/wordpress
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          php wp-cli.phar core config --dbname=woocommerce_test --dbuser=root --dbpass='root' --dbhost=localhost --dbprefix=wp_
          php wp-cli.phar core install --url="http://localhost:8080" --title="Example" --admin_user=admin --admin_password=password --admin_email=info@example.com --path=/tmp/wordpress --skip-email
          php wp-cli.phar plugin install /tmp/woocommerce.zip --activate
          php wp-cli.phar plugin install /tmp/swedbank-pay-woocommerce-checkout.zip --activate

      - name: Run tests
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PAYEE_ID: ${{ secrets.PAYEE_ID }}
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_RUN_CORE_TESTS: 1
        run: |
          if [ "$ACCESS_TOKEN" != "" ]; then
            cd $GITHUB_WORKSPACE/swedbank-pay-woocommerce-checkout
            WOOCOMMERCE_DIR=$GITHUB_WORKSPACE/woocommerce phpunit --configuration=./tests/phpunit.xml --bootstrap=./tests/bootstrap.php --coverage-clover=coverage.xml
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            /tmp/wordpress/wp-content/uploads/wc-logs/*.log
            /tmp/swedbank-pay-woocommerce-checkout.zip

      - name: Upload code coverage report to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
